type NotExistingUserException* = object of CatchableError
